# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base:
  sidekiq:
    :username:
    :password:
  database:
    :database:
    :socket:
    :username:
    :password:
  smtp_settings:
    :domain:
    :user_name:
    :password:
  emails:
    :from:
    :to:

test:
  secret_key_base:
  database:
    :database:
    :socket:
    :username:
    :password:
  sidekiq:
    :username:
    :password:
  smtp_settings:
    :domain:
    :user_name:
    :password:
  emails:
    :from:
    :to:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:
  database:
    :database:
    :socket:
    :username:
    :password:
  capistrano:
    :deploy_to:
    :server:
    :user:
  sidekiq:
    :username:
    :password:
  smtp_settings:
    :domain:
    :user_name:
    :password:
  emails:
    :from:
    :to:
